name: CI

on:
  push:
    branches: [main]
#  pull_request:
#    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_DB: testing_helper
          POSTGRES_USER: khun
          POSTGRES_PASSWORD: khun
        ports:
          - 5332:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    




  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Run Unit/Integration Tests with maven
        run: mvn -ntp -B verify